// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: temporal/api/cloud/resource/v1/message.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

package enum Temporal_Api_Cloud_Resource_V1_ResourceState: SwiftProtobuf.Enum, Swift.CaseIterable {
  package typealias RawValue = Int
  case unspecified // = 0

  /// The resource is being activated.
  case activating // = 1

  /// The resource failed to activate. This is an error state. Reach out to support for remediation.
  case activationFailed // = 2

  /// The resource is active and ready to use.
  case active // = 3

  /// The resource is being updated.
  case updating // = 4

  /// The resource failed to update. This is an error state. Reach out to support for remediation.
  case updateFailed // = 5

  /// The resource is being deleted.
  case deleting // = 6

  /// The resource failed to delete. This is an error state. Reach out to support for remediation.
  case deleteFailed // = 7

  /// The resource has been deleted.
  case deleted // = 8

  /// The resource is suspended and not available for use. Reach out to support for remediation.
  case suspended // = 9

  /// The resource has expired and is no longer available for use.
  case expired // = 10
  case UNRECOGNIZED(Int)

  package init() {
    self = .unspecified
  }

  package init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .activating
    case 2: self = .activationFailed
    case 3: self = .active
    case 4: self = .updating
    case 5: self = .updateFailed
    case 6: self = .deleting
    case 7: self = .deleteFailed
    case 8: self = .deleted
    case 9: self = .suspended
    case 10: self = .expired
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  package var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .activating: return 1
    case .activationFailed: return 2
    case .active: return 3
    case .updating: return 4
    case .updateFailed: return 5
    case .deleting: return 6
    case .deleteFailed: return 7
    case .deleted: return 8
    case .suspended: return 9
    case .expired: return 10
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  package static let allCases: [Temporal_Api_Cloud_Resource_V1_ResourceState] = [
    .unspecified,
    .activating,
    .activationFailed,
    .active,
    .updating,
    .updateFailed,
    .deleting,
    .deleteFailed,
    .deleted,
    .suspended,
    .expired,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Temporal_Api_Cloud_Resource_V1_ResourceState: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RESOURCE_STATE_UNSPECIFIED\0\u{1}RESOURCE_STATE_ACTIVATING\0\u{1}RESOURCE_STATE_ACTIVATION_FAILED\0\u{1}RESOURCE_STATE_ACTIVE\0\u{1}RESOURCE_STATE_UPDATING\0\u{1}RESOURCE_STATE_UPDATE_FAILED\0\u{1}RESOURCE_STATE_DELETING\0\u{1}RESOURCE_STATE_DELETE_FAILED\0\u{1}RESOURCE_STATE_DELETED\0\u{1}RESOURCE_STATE_SUSPENDED\0\u{1}RESOURCE_STATE_EXPIRED\0")
}
