// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: temporal/api/enums/v1/nexus.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// NexusHandlerErrorRetryBehavior allows nexus handlers to explicity set the retry behavior of a HandlerError. If not
/// specified, retry behavior is determined from the error type. For example internal errors are not retryable by default
/// unless specified otherwise.
package enum Temporal_Api_Enums_V1_NexusHandlerErrorRetryBehavior: SwiftProtobuf.Enum, Swift.CaseIterable {
  package typealias RawValue = Int
  case unspecified // = 0

  /// A handler error is explicitly marked as retryable.
  case retryable // = 1

  /// A handler error is explicitly marked as non-retryable.
  case nonRetryable // = 2
  case UNRECOGNIZED(Int)

  package init() {
    self = .unspecified
  }

  package init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .retryable
    case 2: self = .nonRetryable
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  package var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .retryable: return 1
    case .nonRetryable: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  package static let allCases: [Temporal_Api_Enums_V1_NexusHandlerErrorRetryBehavior] = [
    .unspecified,
    .retryable,
    .nonRetryable,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Temporal_Api_Enums_V1_NexusHandlerErrorRetryBehavior: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NEXUS_HANDLER_ERROR_RETRY_BEHAVIOR_UNSPECIFIED\0\u{1}NEXUS_HANDLER_ERROR_RETRY_BEHAVIOR_RETRYABLE\0\u{1}NEXUS_HANDLER_ERROR_RETRY_BEHAVIOR_NON_RETRYABLE\0")
}
