// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: temporal/api/enums/v1/command_type.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Whenever this list of command types is changed do change the function shouldBufferEvent in mutableStateBuilder.go to make sure to do the correct event ordering.
package enum Temporal_Api_Enums_V1_CommandType: SwiftProtobuf.Enum, Swift.CaseIterable {
  package typealias RawValue = Int
  case unspecified // = 0
  case scheduleActivityTask // = 1
  case requestCancelActivityTask // = 2
  case startTimer // = 3
  case completeWorkflowExecution // = 4
  case failWorkflowExecution // = 5
  case cancelTimer // = 6
  case cancelWorkflowExecution // = 7
  case requestCancelExternalWorkflowExecution // = 8
  case recordMarker // = 9
  case continueAsNewWorkflowExecution // = 10
  case startChildWorkflowExecution // = 11
  case signalExternalWorkflowExecution // = 12
  case upsertWorkflowSearchAttributes // = 13
  case protocolMessage // = 14
  case modifyWorkflowProperties // = 16
  case scheduleNexusOperation // = 17
  case requestCancelNexusOperation // = 18
  case UNRECOGNIZED(Int)

  package init() {
    self = .unspecified
  }

  package init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .scheduleActivityTask
    case 2: self = .requestCancelActivityTask
    case 3: self = .startTimer
    case 4: self = .completeWorkflowExecution
    case 5: self = .failWorkflowExecution
    case 6: self = .cancelTimer
    case 7: self = .cancelWorkflowExecution
    case 8: self = .requestCancelExternalWorkflowExecution
    case 9: self = .recordMarker
    case 10: self = .continueAsNewWorkflowExecution
    case 11: self = .startChildWorkflowExecution
    case 12: self = .signalExternalWorkflowExecution
    case 13: self = .upsertWorkflowSearchAttributes
    case 14: self = .protocolMessage
    case 16: self = .modifyWorkflowProperties
    case 17: self = .scheduleNexusOperation
    case 18: self = .requestCancelNexusOperation
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  package var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .scheduleActivityTask: return 1
    case .requestCancelActivityTask: return 2
    case .startTimer: return 3
    case .completeWorkflowExecution: return 4
    case .failWorkflowExecution: return 5
    case .cancelTimer: return 6
    case .cancelWorkflowExecution: return 7
    case .requestCancelExternalWorkflowExecution: return 8
    case .recordMarker: return 9
    case .continueAsNewWorkflowExecution: return 10
    case .startChildWorkflowExecution: return 11
    case .signalExternalWorkflowExecution: return 12
    case .upsertWorkflowSearchAttributes: return 13
    case .protocolMessage: return 14
    case .modifyWorkflowProperties: return 16
    case .scheduleNexusOperation: return 17
    case .requestCancelNexusOperation: return 18
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  package static let allCases: [Temporal_Api_Enums_V1_CommandType] = [
    .unspecified,
    .scheduleActivityTask,
    .requestCancelActivityTask,
    .startTimer,
    .completeWorkflowExecution,
    .failWorkflowExecution,
    .cancelTimer,
    .cancelWorkflowExecution,
    .requestCancelExternalWorkflowExecution,
    .recordMarker,
    .continueAsNewWorkflowExecution,
    .startChildWorkflowExecution,
    .signalExternalWorkflowExecution,
    .upsertWorkflowSearchAttributes,
    .protocolMessage,
    .modifyWorkflowProperties,
    .scheduleNexusOperation,
    .requestCancelNexusOperation,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Temporal_Api_Enums_V1_CommandType: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COMMAND_TYPE_UNSPECIFIED\0\u{1}COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK\0\u{1}COMMAND_TYPE_REQUEST_CANCEL_ACTIVITY_TASK\0\u{1}COMMAND_TYPE_START_TIMER\0\u{1}COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION\0\u{1}COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION\0\u{1}COMMAND_TYPE_CANCEL_TIMER\0\u{1}COMMAND_TYPE_CANCEL_WORKFLOW_EXECUTION\0\u{1}COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION\0\u{1}COMMAND_TYPE_RECORD_MARKER\0\u{1}COMMAND_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION\0\u{1}COMMAND_TYPE_START_CHILD_WORKFLOW_EXECUTION\0\u{1}COMMAND_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION\0\u{1}COMMAND_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES\0\u{1}COMMAND_TYPE_PROTOCOL_MESSAGE\0\u{2}\u{2}COMMAND_TYPE_MODIFY_WORKFLOW_PROPERTIES\0\u{1}COMMAND_TYPE_SCHEDULE_NEXUS_OPERATION\0\u{1}COMMAND_TYPE_REQUEST_CANCEL_NEXUS_OPERATION\0")
}
