name: Main

permissions:
  contents: read

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8,20 * * *"

jobs:
  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_5_10_enabled: false
      linux_6_0_enabled: false
      linux_6_1_enabled: false
      linux_6_2_arguments_override: "-Xswiftc -require-explicit-sendable"
      linux_nightly_next_arguments_override: "-Xswiftc -require-explicit-sendable"
      linux_nightly_main_arguments_override: "-Xswiftc -require-explicit-sendable"

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main
    with:
      linux_5_10_enabled: false
      linux_6_0_enabled: false
      linux_6_1_enabled: false

  release-builds:
    name: Release builds
    uses: apple/swift-nio/.github/workflows/release_builds.yml@main
    with:
      linux_5_10_enabled: false
      linux_6_0_enabled: false
      linux_6_1_enabled: false
